language: en
pipeline:
- name: "WhitespaceTokenizer"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "CountVectorsFeaturizer"
- name: "DIETClassifier"
policies:
  - name: MemoizationPolicy
  # - name: MappingPolicy
  - name: RulePolicy
  # - name: EmbeddingPolicy
  # - name: FormPolicy
  # - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
